import * as React from 'react';

export class ListComponent extends React.Component<any, any> {
    public render() {
        return (
            <div className="container">
                <table className="table">
                    <tr data-toggle="collapse" data-target="#more-info-1" className="accordion-toggle" >
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr>
                    <tr>
                        <td colSpan={6} className="hidden-row" >
                            <div className="accordion-body-collapse" id="more-info-1" >Sample</div>
                        </td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr>
                    <tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr>
                </table>
            </div>
        )
    }
}