import * as React from 'react';
// import { ListComponent } from './list/list-component';

export class RequestListComponent extends React.Component<any, any> {
    public render() {
        return (
            <div className="container" id="main-menu">
                <h1>Hello, Scott</h1>
                <h2>You have submitted 3 requests</h2>
                <div className="container">
                <table className="table">
                    <tr data-toggle="collapse" data-target="#more-info-1" className="accordion-toggle" >
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr>
                    <tr>
                        <td colSpan={6} className="hidden-row" >
                            <div className="accordion-body-collapse" id="more-info-1" >Sample</div>
                        </td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr>
                    <tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr><tr>
                        <td>thing</td>
                        <td>thing</td>
                        <td>thing</td>
                    </tr>
                </table>
            </div>
            </div>
        )
    }
}