export const requestTypes = {
  UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',
  UPDATE_FORM: 'UPDATE_FORM',
  UPDATE_MOVIES: 'UPDATE_MOVIES',
  UPDATE_RATING: 'UPDATE_RATING',
  UPDATE_TITLE: 'UPDATE_TITLE',
  UPDATE_YEAR: 'UPDATE_YEAR',
    
  }