export const requestTypes = {
  UPDATE_AMOUNT: 'UPDATE_AMOUNT',
  UPDATE_DATE: 'UPDATE_DATE',
  UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',
  UPDATE_FORM: 'UPDATE_FORM',
  UPDATE_LIST: 'UPDATE_LIST',
  UPDATE_MOVIES: 'UPDATE_MOVIES',
  UPDATE_RATING: 'UPDATE_RATING',
  UPDATE_TITLE: 'UPDATE_TITLE',
  UPDATE_TYPE: 'UPDATE_TYPE',
  UPDATE_YEAR: 'UPDATE_YEAR',
    
  }